<?php

namespace Database\Seeders;

use App\Models\SandsMenu;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class SandsMenuSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $menus = [
            [
                'main_title' => 'Avocado Prawn Refresh',
                'description' => 'Poached prawn with avocado, edamame, sweet corn, cherry tomato, lettuce served with honey lime dressing',
                'title_1' => null,
                'title_2' => null,
                'title_3' => null,
                'title_4' => null,
                'price_1' => 115000,
                'price_2' => null,
                'price_3' => null,
                'price_4' => null,
                'image' => 'https://anvayabali.com/anvayamenu/yummy/assets/img/menu/menuicons_avocadoprawnrefresh.png',
                'video_url' => 'https://anvayabali.com/anvayamenu/sands/salad/avocadoprawnrefresh.mp4',
                'category_sands_id' => 1,
                'tag_id' => 1,
                'status'=> true,
                'user_id'=> 1,
            ],
            [
                'main_title' => 'Classic Caesar Salad',
                'description' => 'Romaine lettuce tossed with caesar dressing, poached egg, parmesan shave, crouton with optional topping : chicken breast, prawn or smoked salmon',
                'title_1' => 'Smoked Salmon',
                'title_2' => 'Prawn',
                'title_3' => 'Chicken',
                'title_4' => null,
                'price_1' => 115000,
                'price_2' => 105000,
                'price_3' => 95000,
                'price_4' => null,
                'image' => 'https://anvayabali.com/anvayamenu/yummy/assets/img/menu/menuicons_caessarsalad.png',
                'video_url' => 'https://anvayabali.com/anvayamenu/sands/salad/caesarchickensalad.mp4',
                'category_sands_id' => 1,
                'tag_id' => 1,
                'status'=> true,
                'user_id'=> 1,
            ],
            [
                'main_title' => 'Poke Bowl Sashimi Salad',
                'description' => 'Tuna salmon sashimi cubes, lettuce, avocado, pomegranate, edamame, red radish, toasted hie sesame seed served with tamanegi dressing',
                'title_1' => null,
                'title_2' => null,
                'title_3' => null,
                'title_4' => null,
                'price_1' => 115000,
                'price_2' => null,
                'price_3' => null,
                'price_4' => null,
                'image' => 'https://anvayabali.com/anvayamenu/yummy/assets/img/menu/menuicons_pokebowl.png',
                'video_url' => 'https://anvayabali.com/anvayamenu/sands/salad/pokebowlsashimisalad.mp4',
                'category_sands_id' => 1,
                'tag_id' => 1,
                'status'=> true,
                'user_id'=> 1,
            ],
            [
                'main_title' => 'Garden Salad',
                'description' => 'Assorted lettuce with avocado, quail egg, potato chip, tomato cherry, string bean, parmesan, shave, onion, olive with optional topping : chicken breast, prawn or smoked salmon',
                'title_1' => 'Smoked Salmon',
                'title_2' => 'Prawn',
                'title_3' => 'Chicken',
                'title_4' => 'Garden Salad',
                'price_1' => 125000,
                'price_2' => 115000,
                'price_3' => 105000,
                'price_4' => 95000,
                'image' => 'https://anvayabali.com/anvayamenu/yummy/assets/img/menu/menuicons_gardensalad.png',
                'video_url' => 'https://anvayabali.com/anvayamenu/sands/salad/gardensalad.mp4',
                'category_sands_id' => 1,
                'tag_id' => 1,
                'status'=> true,
                'user_id'=> 1,
            ],
            [
                'main_title' => 'Charcuterie And Cheese Platter',
                'description' => 'Prosciutto, salami, chorizo, parmesan, emmental, camembert, grill sour dough, wild rucolla, black and green olive, local grape, date jam',
                'title_1' => null,
                'title_2' => null,
                'title_3' => null,
                'title_4' => null,
                'price_1' => 285000,
                'price_2' => null,
                'price_3' => null,
                'price_4' => null,
                'image' => 'https://anvayabali.com/anvayamenu/yummy/assets/img/menu/menuiconschefbasket_cheeseplatter.png',
                'video_url' => 'https://anvayabali.com/anvayamenu/sands/lightbites/charcuterieandcheese.mp4',
                'category_sands_id' => 2,
                'tag_id' => 1,
                'status'=> true,
                'user_id'=> 1,
            ],
            [
                'main_title' => 'Fish And Chip (from 12 noon until 6 p.m.)',
                'description' => 'Deep fried fish beer batter, french fries, lettuce, spicy sesame, ginger tartar dipping',
                'title_1' => null,
                'title_2' => null,
                'title_3' => null,
                'title_4' => null,
                'price_1' => 95000,
                'price_2' => null,
                'price_3' => null,
                'price_4' => null,
                'image' => 'https://anvayabali.com/anvayamenu/yummy/assets/img/menu/menuiconschefbasket_fishandchip.png',
                'video_url' => 'https://anvayabali.com/anvayamenu/sands/lightbites/fishandchip.mp4',
                'category_sands_id' => 2,
                'tag_id' => 1,
                'status'=> true,
                'user_id'=> 1,
            ],
            [
                'main_title' => 'BBQ Chicken Wing (from 12 noon until 6 p.m.)',
                'description' => 'five pcs barbeque chicken wings, potato wedges, lettuce, spicy sesame, BBQ sauce',
                'title_1' => null,
                'title_2' => null,
                'title_3' => null,
                'title_4' => null,
                'price_1' => 95000,
                'price_2' => null,
                'price_3' => null,
                'price_4' => null,
                'image' => 'https://anvayabali.com/anvayamenu/yummy/assets/img/menu/menuiconschefbasket_bbqchickenwing.png',
                'video_url' => 'https://anvayabali.com/anvayamenu/sands/lightbites/bbqchickenwing.mp4',
                'category_sands_id' => 2,
                'tag_id' => 1,
                'status'=> true,
                'user_id'=> 1,
            ],
            [
                'main_title' => 'Calamari And Onion Ring (from 12 noon until 6 p.m.)',
                'description' => 'Deep fried calamari and onion ring, romaine lettuce, spicy sesame, ginger tartar dipping',
                'title_1' => null,
                'title_2' => null,
                'title_3' => null,
                'title_4' => null,
                'price_1' => 95000,
                'price_2' => null,
                'price_3' => null,
                'price_4' => null,
                'image' => 'https://anvayabali.com/anvayamenu/yummy/assets/img/menu/menuiconschefbasket_calamary.png',
                'video_url' => 'https://anvayabali.com/anvayamenu/sands/lightbites/calamariandonionring.mp4',
                'category_sands_id' => 2,
                'tag_id' => 1,
                'status'=> true,
                'user_id'=> 1,
            ],


        ];

        SandsMenu::insert($menus);
    }
}
